INCLUDE( CheckFunctionExists )
INCLUDE( CheckIncludeFile )
INCLUDE( CheckIncludeFiles )
INCLUDE( CheckSymbolExists )
INCLUDE( CheckCCompilerFlag )
INCLUDE( CheckLibraryExists )


CHECK_INCLUDE_FILE( inttypes.h HAVE_INTTYPES_H )
CHECK_INCLUDE_FILE( memory.h HAVE_MEMORY_H )
CHECK_INCLUDE_FILE( stdint.h HAVE_STDINT_H )
CHECK_INCLUDE_FILE( stdlib.h HAVE_STDLIB_H )
CHECK_INCLUDE_FILE( strings.h HAVE_STRINGS_H )
CHECK_INCLUDE_FILE( string.h HAVE_STRING_H )
CHECK_INCLUDE_FILE( sys/stat.h HAVE_SYS_STAT_H )
CHECK_INCLUDE_FILE( sys/types.h HAVE_SYS_TYPES_H )

CHECK_FUNCTION_EXISTS( strndup HAVE_STRNDUP )
CHECK_FUNCTION_EXISTS( wcsdup HAVE_WCSDUP )

IF( WIN32 )
	SET( X_DISPLAY_MISSING 0 )
ELSE( WIN32 )
	SET( X_DISPLAY_MISSING 1 )
ENDIF( WIN32 )

